# Generated by Django 5.0.6 on 2024-06-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appointment_contactus_usermail'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactusnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(max_length=14)),
                ('existing_customer', models.CharField(max_length=100, null=True)),
                ('enquiry_type', models.CharField(max_length=100, null=True)),
                ('callback_team', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
